#!/bin/sh

OUTPUT="/tmp/test-$(date +%s)"
######## KTLINT-GRADLE HOOK START ########
CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}')"

if [ -z "$CHANGED_FILES" ]; then
    echo "No Kotlin staged files."
    exit 0
fi;

echo "*************************************************"
echo "          Running ktlint over these files:       "
echo "$CHANGED_FILES"
echo "*************************************************"
echo ""
echo ""

./gradlew ktlintFormat -PinternalKtlintGitFilter="$CHANGED_FILES" > "$OUTPUT"
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat "$OUTPUT"
  rm "$OUTPUT"
  echo "*************************************************"
  echo "              ktlintFormat failed :(             "
  echo " Please fix the failing format before committing "
  echo "*************************************************"
  exit $EXIT_CODE
fi
  echo "*************************************************"
  echo "              ktlintFormat success :)            "
  echo "*************************************************"
  echo ""
  echo ""
  echo "$CHANGED_FILES" | while read -r file; do
      if [ -f "$file" ]; then
          git add "$file"
      fi
  done

echo "Completed ktlint hook."
######## KTLINT-GRADLE HOOK END ########